INSERT INTO Categories (ParentId, Name, Logo, IsEnableEcommerce, StatusId, UserId, ExternalId, CreatedAt, UpdatedAt) VALUES
(0, 'Electrónica', 'http://example.com/logo_electronica.jpg', 1, 1, 1, 2001, GETDATE(), GETDATE()),
(1, 'Televisores', 'http://example.com/logo_televisores.jpg', 1, 1, 1, 2002, GETDATE(), GETDATE()),
(1, 'Computadoras', 'http://example.com/logo_computadoras.jpg', 1, 1, 1, 2003, GETDATE(), GETDATE()),
(1, 'Teléfonos Móviles', 'http://example.com/logo_telefonos_mobiles.jpg', 1, 1, 1, 2004, GETDATE(), GETDATE()),
(2, 'LED', 'http://example.com/logo_led.jpg', 1, 1, 1, 2005, GETDATE(), GETDATE()),
(2, 'OLED', 'http://example.com/logo_oled.jpg', 1, 1, 1, 2006, GETDATE(), GETDATE()),
(3, 'Portátiles', 'http://example.com/logo_portatiles.jpg', 1, 1, 1, 2007, GETDATE(), GETDATE()),
(3, 'Sobremesa', 'http://example.com/logo_sobremesa.jpg', 1, 1, 1, 2008, GETDATE(), GETDATE()),
(4, 'Android', 'http://example.com/logo_android.jpg', 1, 1, 1, 2009, GETDATE(), GETDATE()),
(4, 'iOS', 'http://example.com/logo_ios.jpg', 1, 1, 1, 2010, GETDATE(), GETDATE()),
(0, 'Accesorios Electrónicos', 'http://example.com/logo_accesorios.jpg', 1, 1, 1, 2011, GETDATE(), GETDATE()),
(11, 'Auriculares', 'http://example.com/logo_auriculares.jpg', 1, 1, 1, 2012, GETDATE(), GETDATE()),
(11, 'Cargadores', 'http://example.com/logo_cargadores.jpg', 1, 1, 1, 2013, GETDATE(), GETDATE()),
(11, 'Fundas', 'http://example.com/logo_fundas.jpg', 1, 1, 1, 2014, GETDATE(), GETDATE()),
(0, 'Electrodomésticos', 'http://example.com/logo_electrodomesticos.jpg', 1, 1, 1, 2015, GETDATE(), GETDATE()),
(15, 'Refrigeradores', 'http://example.com/logo_refrigeradores.jpg', 1, 1, 1, 2016, GETDATE(), GETDATE()),
(15, 'Lavadoras', 'http://example.com/logo_lavadoras.jpg', 1, 1, 1, 2017, GETDATE(), GETDATE()),
(15, 'Microondas', 'http://example.com/logo_microondas.jpg', 1, 1, 1, 2018, GETDATE(), GETDATE()),
(0, 'Videojuegos', 'http://example.com/logo_videojuegos.jpg', 1, 1, 1, 2019, GETDATE(), GETDATE()),
(19, 'Consolas', 'http://example.com/logo_consolas.jpg', 1, 1, 1, 2020, GETDATE(), GETDATE());
