ALTER TABLE Branches ADD FOREIGN KEY (StatusId) REFERENCES CatStatus(Id)
ALTER TABLE Branches ADD FOREIGN KEY (UserId) REFERENCES Users(Id)
ALTER TABLE Branches ADD FOREIGN KEY (CompanyId) REFERENCES Companies(Id)
