ALTER TABLE Products ADD FOREIGN KEY (StatusId) REFERENCES CatStatus(Id)
ALTER TABLE Products ADD FOREIGN KEY (UserId) REFERENCES Users(Id)
ALTER TABLE Products ADD FOREIGN KEY (BrandId) REFERENCES Brands(Id)