
ALTER TABLE RelRoleFrontRoutes ADD FOREIGN KEY (RoleId) REFERENCES Roles(Id)

ALTER TABLE RelRoleFrontRoutes ADD FOREIGN KEY (RouteId) REFERENCES FrontendRoutes(Id)

ALTER TABLE RelRoleFrontRoutes ADD FOREIGN KEY (UserId) REFERENCES Users(Id)