
SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (1,'Activo')
SET IDENTITY_INSERT CatStatus OFF

GO
SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (2,'Eliminado') 
SET IDENTITY_INSERT CatStatus OFF

GO 

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (3,'Bloqueado') 
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (4,'Pendiente') 
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (5,'Vencido') 
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (6,'Cobro') 
SET IDENTITY_INSERT CatStatus OFF

GO 

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (7,'Cobro Pendiente') 
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (8,'En Proceso')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (9,'Finalizado')
SET IDENTITY_INSERT CatStatus OFF
	
GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (10,'Auditado') 
SET IDENTITY_INSERT CatStatus OFF
	
GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (11,'Recolección')
SET IDENTITY_INSERT CatStatus OFF
	
GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (12,'Empacado En Proceso')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (13,'Empacado Finalizado')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (14,'Guia En Proceso')
SET IDENTITY_INSERT CatStatus OFF
	
GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (15,'Guia Generada')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (16,'Guia Pegada')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (17,'Archivado')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (18,'Pago Sin Proceso')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (19,'Cancelado')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (20,'Pago Validado')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (21,'Validado Por Seguridad')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (22,'Pago no valido')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (23,'Agotados')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (24,'Agotados y por llegar')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (25,'Surtido')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (26,'Pendiente por validar')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (27,'En Proceso de Validación')
SET IDENTITY_INSERT CatStatus OFF

GO

SET IDENTITY_INSERT CatStatus ON
INSERT INTO CatStatus(Id,Name) 	VALUES (28,'Pedido Validado')
SET IDENTITY_INSERT CatStatus OFF