SET IDENTITY_INSERT SatStates ON
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 83,40,'ON','CAN','Ontario ',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 84,40,'QC','CAN',' Quebec ',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 85,40,'NS','CAN',' Nueva Escocia',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 86,40,'NB','CAN','Nuevo Brunswick ',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 87,40,'MB','CAN',' Manitoba',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 88,40,'BC','CAN',' Columbia Británica',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 89,40,'PE','CAN',' Isla del Príncipe Eduardo',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 90,40,'SK','CAN',' Saskatchewan',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 91,40,'AB','CAN',' Alberta',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 92,40,'NL','CAN',' Terranova y Labrador',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 93,40,'NT','CAN',' Territorios del Noroeste',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 94,40,'YT','CAN',' Yukón',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 95,40,'UN','CAN',' Nunavut',1)
SET IDENTITY_INSERT SatStates OFF