SET IDENTITY_INSERT SatStates ON
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 33,66,'AL','USA','Alabama',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 34,66,'AK','USA','Alaska',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 35,66,'AZ','USA','Arizona',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 36,66,'AR','USA','Arkansas',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 37,66,'CA','USA','California',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 38,66,'NC','USA','Carolina del Norte',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 39,66,'SC','USA','Carolina del Sur',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 40,66,'CO','USA','Colorado',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 41,66,'CT','USA','Connecticut',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 42,66,'ND','USA','Dakota del Norte',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 43,66,'SD','USA','Dakota del Sur',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 44,66,'DE','USA','Delaware',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 45,66,'FL','USA','Florida',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 46,66,'GA','USA','Georgia',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 47,66,'HI','USA','Hawái',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 48,66,'ID','USA','Idaho',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 49,66,'IL','USA','Illinois',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 50,66,'IN','USA','Indiana',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 51,66,'IA','USA','Iowa',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 52,66,'KS','USA','Kansas',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 53,66,'KY','USA','Kentucky',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 54,66,'LA','USA','Luisiana',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 55,66,'ME','USA','Maine',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 56,66,'MD','USA','Maryland',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 57,66,'MA','USA','Massachusetts',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 58,66,'MI','USA','Míchigan',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 59,66,'MN','USA','Minnesota',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 60,66,'MS','USA','Misisipi',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 61,66,'MO','USA','Misuri',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 62,66,'MT','USA','Montana',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 63,66,'NE','USA','Nebraska',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 64,66,'NV','USA','Nevada',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 65,66,'NJ','USA','Nueva Jersey',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 66,66,'NY','USA','Nueva York',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 67,66,'NH','USA','Nuevo Hampshire',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 68,66,'NM','USA','Nuevo México',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 69,66,'OH','USA','Ohio',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 70,66,'OK','USA','Oklahoma',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 71,66,'OR','USA','Oregón',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 72,66,'PA','USA','Pensilvania',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 73,66,'RI','USA','Rhode Island',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 74,66,'TN','USA','Tennessee',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 75,66,'TX','USA','Texas',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 76,66,'UT','USA','Utah',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 77,66,'VT','USA','Vermont',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 78,66,'VA','USA','Virginia',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 79,66,'WV','USA','Virginia Occidental',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 80,66,'WA','USA','Washington',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 81,66,'WI','USA','Wisconsin',1)
INSERT INTO SatStates (Id,CountryId,Code,CountryCode,Name,StatusId) VALUES ( 82,66,'WY','USA','Wyoming',1)
SET IDENTITY_INSERT SatStates OFF