CREATE TABLE BankAccounts(
	Id INT PRIMARY KEY IDENTITY(1,1) ,
	CompanyId INT NOT NULL , 
	BankName VARCHAR(300) , 	
	AccountNumber VARCHAR(100) NOT NULL UNIQUE , 
	InterbankKey VARCHAR(100) NOT NULL UNIQUE , 
	CreateAt DATETIME2 NOT NULL DEFAULT GETDATE() , 
	UpdateAt DATETIME2 NOT NULL DEFAULT GETDATE() ,
	UserId INT NOT NULL ,
	StatusId INT NOT NULL  DEFAULT 1 
)