CREATE TABLE CatOrderStatusCone(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(200) NOT NULL ,
	Color  VARCHAR(50) NOT NULL ,
	ConeKey VARCHAR(200) NOT NULL ,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE() 
)
