CREATE TABLE Customers(
    Id INT PRIMARY KEY IDENTITY(1,1) ,
    Code VARCHAR(50) NOT NULL , 
    FirstName VARCHAR(250) NOT NULL , 
    LastName VARCHAR(250) NOT NULL , 
    Phone VARCHAR(15) , 
    Email VARCHAR(250) , 
    Address VARCHAR(500) , 
    ZipCode VARCHAR(10) , 
    InteriorNumber VARCHAR(20) , 
    ExteriorNumber VARCHAR(20) , 
    Commentary VARCHAR(500) ,
    CountryId INT NOT NULL ,     
    StateId INT NOT NULL , 
    TaxId VARCHAR(20) ,
    TaxZipCode VARCHAR(10) ,
    TaxName VARCHAR(250) ,
    TaxEmail VARCHAR(250) ,
    TaxRegimeCode VARCHAR(50) ,
    TaxUseCode VARCHAR(50) ,   
    StatusId INT NOT NULL ,
    UserId INT NOT NULL ,
    ExternalId INT NOT NULL DEFAULT 0 ,    
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)