CREATE TABLE Departments (
    Id INT PRIMARY KEY IDENTITY(1,1),
    AccountId INT NOT NULL , 
    Name VARCHAR(250) NOT NULL,
    ManagerId INT NULL,    
    StatusId INT NOT NULL DEFAULT 1 , 
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
