CREATE TABLE OrdersTrackerFedEx(
	Id INT PRIMARY KEY IDENTITY(1,1) , 
	OrderId INT NOT NULL , 
	BoxId INT NOT NULL  , 
	TrackerNumber VARCHAR(200) NOT NULL ,
	TrackerUrl VARCHAR(250) NOT NULL ,
	UserId INT NOT NULL , 
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE() , 
	UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
)