CREATE TABLE OrderLocationsLayout(
	Id INT PRIMARY KEY IDENTITY(1,1) ,
	WarehouseId INT NOT NULL , 
	Name VARCHAR(250) NOT NULL , 	
	StatusId INT NOT NULL , 
	UserId INT NOT NULL ,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE() 
)