CREATE TABLE Permissions (
    Id INT PRIMARY KEY IDENTITY(1,1),
    RoleId INT NOT NULL,
    RouteId INT NOT NULL,
    ActionId INT NOT NULL,	
	CreateAt DATETIME2 NOT NULL DEFAULT GETDATE() ,
	UpdateAt DATETIME2 NOT NULL DEFAULT GETDATE() 
);