CREATE TABLE Products(
    Id  INT PRIMARY KEY IDENTITY(1,1) , 
    Code VARCHAR(100) , 
    Name VARCHAR(250) , 
    Description VARCHAR(500) , 
    Model VARCHAR(100) , 
    ImageUrl VARCHAR(250) , 
    Barcode  VARCHAR(50) , 
    Price DECIMAL(18,2) ,
    PriceWholesale DECIMAL(18,2) ,
    PriceMember DECIMAL(18,2) ,
    PriceBox DECIMAL(18,2) ,
    PriceVip DECIMAL(18,2) ,
    PricePremium DECIMAL(18,2) ,
    PricePlus DECIMAL(18,2) ,
    LowerPrice DECIMAL(18,2) ,
    Width DECIMAL(18,2) ,
    Height DECIMAL(18,2) ,
    Weight DECIMAL(18,2) ,
    EnableWeb int not null default 0 ,
    EnableInvoice int not null default 0 ,
    SatUseCode VARCHAR(10) ,
    SatUnitCode VARCHAR(10) ,
    BrandId INT NOT NULL ,
    StatusId INT NOT NULL ,
    UserId INT NOT NULL , 
    ExternalId INT NOT NULL DEFAULT 0 ,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)