CREATE TABLE ProductsGallery(
    Id  INT PRIMARY KEY AUTO_INCREMENT , 
    ProductId INT NOT NULL , 
    ImageUrl VARCHAR(500) ,
    UserId INT NOT NULL , 
    CreatedAt DATETIME NOT NULL DEFAULT NOW() , 
    UpdatedAt DATETIME NOT NULL DEFAULT NOW()
)