CREATE TABLE Products(
    Id  INT PRIMARY KEY IDENTITY(1,1) , 
    AccountId INT NOT NULL , 
    Code VARCHAR(100) , 
    Name VARCHAR(250) , 
    Description VARCHAR(500) , 
    Model VARCHAR(100) ,
    ImagePublicId VARCHAR(200) ,   
    ImageUrl VARCHAR(250) , 
    Barcode  VARCHAR(50) ,     
    Width DECIMAL(18,2) ,
    Height DECIMAL(18,2) ,
    Weight DECIMAL(18,2) ,
    EnableWeb INT NOT NULL DEFAULT 0 ,
    EnableInvoice INT NOT NULL DEFAULT 0 ,
    SatUseCode VARCHAR(10) ,
    SatUnitCode VARCHAR(10) ,
    BrandId INT NOT NULL ,
    StatusId INT NOT NULL ,
    UserId INT NOT NULL , 
    ExternalId INT NOT NULL DEFAULT 0 ,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
)