CREATE TABLE RelRoleWarehouse (
    Id INT PRIMARY KEY IDENTITY(1,1),
    RoleId INT NOT NULL,
    WarehouseId INT NOT NULL DEFAULT 1,
    IsDefault INT NOT NULL , 
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);