CREATE TABLE RelRoleRoutes(
    Id INT PRIMARY KEY IDENTITY(1,1) , 
    RoleId  INT NOT NULL , 
    RouteId  INT NOT NULL , 
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE() 
)