CREATE TABLE RelRoleFrontRoutes(
    Id INT PRIMARY KEY AUTO_INCREMENT , 
    RoleId  INT NOT NULL , 
    RouteId  INT NOT NULL , 
    UserId INT NOT NULL , 
    CreatedAt DATETIME NOT NULL DEFAULT NOW() , 
    UpdatedAt DATETIME NOT NULL DEFAULT NOW() 
)