CREATE TABLE RelRoleFrontRoutes(
    Id INT PRIMARY KEY IDENTITY(1,1) , 
    RoleId  INT NOT NULL , 
    RouteId  INT NOT NULL , 
    UserId INT NOT NULL , 
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE() 
)