CREATE TABLE RelRoleAccounts (
    Id INT PRIMARY KEY IDENTITY(1,1),
    RoleId VARCHAR(250) NOT NULL,
    AccountId INT NOT NULL DEFAULT 1,
    IsDefault INT NOT NULL , 
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);