CREATE TABLE Roles(
    Id INT PRIMARY KEY IDENTITY(1,1) , 
    Name VARCHAR(250) , 
    StatusId INT NOT NULL , 
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE() ,
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
)