CREATE TABLE Roles(
    Id INT PRIMARY KEY AUTO_INCREMENT , 
    Name VARCHAR(250) , 
    StatusId INT NOT NULL , 
    CreatedAt DATETIME NOT NULL DEFAULT NOW() ,
    UpdatedAt DATETIME NOT NULL DEFAULT NOW() , 
)