CREATE TABLE SalesOrders(
    Id  INT PRIMARY KEY IDENTITY(1,1) , 
    OrderNumber INT NOT NULL , 
    QuoteId INT NOT NULL ,
    CompanyId INT NOT NULL ,
    BranchId INT NOT NULL , 
    WarehouseId INT NOT NULL , 
    CustomerId INT NOT NULL ,
    UserId INT NULL ,
    StatusId INT NULL ,
    Commentary VARCHAR(500) NULL ,    
    ShippingCompany VARCHAR(50) ,
    PriceId INT NOT NULL ,
    Quantity INT NOT NULL ,
    SubTotal DECIMAL(16, 6) NULL ,
    Total DECIMAL(16, 6) NULL ,
    TotalDeliver DECIMAL(16, 6) NULL ,
    TotalAssured DECIMAL(16, 6) NULL ,
    CheckPlusRequired BIT NOT NULL ,
    DeliverRequired BIT NOT NULL ,
    Address VARCHAR(500) ,
    ZipCode VARCHAR(15) ,
    Region VARCHAR(500) ,
    State VARCHAR(100) ,
    City VARCHAR(200) ,
    ExteriorNumber VARCHAR(50) ,
    InteriorNumber VARCHAR(50) ,
    Phone VARCHAR(200) ,
    RequirePacking BIT NOT NULL ,    
    IsPacked BIT NULL ,
    IsAssigned BIT NOT NULL  ,
    PackingComments VARCHAR(250) NULL ,
    CountEdits INT NOT NULL DEFAULT 0 ,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE() ,
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
)