CREATE TABLE SatStates(
    Id INT PRIMARY KEY AUTO_INCREMENT ,
    CountryId INT NOT NULL , 
    Code VARCHAR(50) NOT NULL ,
    CountryCode VARCHAR(50) NOT NULL ,
    Name VARCHAR(250) NOT NULL ,
    StatusId INT NOT NULL ,
    CreatedAt DATETIME NOT NULL DEFAULT NOW() , 
    UpdatedAt DATETIME NOT NULL DEFAULT NOW() 
)