CREATE TABLE SatStates(
    Id INT PRIMARY KEY IDENTITY(1,1) ,
    CountryId INT NOT NULL , 
    Code VARCHAR(50) NOT NULL ,
    CountryCode VARCHAR(50) NOT NULL ,
    Name VARCHAR(250) NOT NULL ,
    StatusId INT NOT NULL ,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE() , 
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE() 
)