CREATE TABLE SatTaxRegime(
    Id INT PRIMARY KEY AUTO_INCREMENT ,
    Code VARCHAR(50) , 
    Name VARCHAR(250) , 
    Version VARCHAR(10) , 
    StatusId INT NOT NULL ,
    CreatedAt DATETIME NOT NULL DEFAULT NOW() , 
    UpdatedAt DATETIME NOT NULL DEFAULT NOW()  
)