/* TODO, fix names */
CREATE TABLE StartnetOrders(
        ID INT PRIMARY KEY IDENTITY(1,1) ,
        ExternalID int ,
        BranchID int NULL,
        BillDate datetime NULL,
        WarehouseID int NULL,
        BillCode varchar(30) NULL,
        CustomBillCode varchar(100) NULL,
        InvoiceType int NULL,
        CustomerID int NULL,
        ShippingAddress varchar(500) NULL,
        ConsigneeName varchar(300) NULL,
        ConsigneeMobile varchar(250) NULL,
        DeliveryDate datetime NULL,
        ExpressCompany varchar(200) NULL,
        ExpressCode varchar(50) NULL,
        Remark varchar(200) NULL,
        Memo varchar(500) NULL,
        BillQuantity decimal(15, 6) NULL,
        BillAmount decimal(15, 6) NULL,
        ModifyTime datetime NULL,
        IsCancelled bit NULL,
        UpdatedAt datetime NULL,
        BranchName varchar(250) NULL,
        WarehouseName varchar(250) NULL,
        HandlerID int NULL,
        HandlerName varchar(250) NULL,
        OrdeAsignada int NULL,
        NIssuesLogs int NOT NULL,
        QuoteID int NULL
)